var gaji = 4500000;
var transport = 10000;
var hari = 24;
var infak = 50000;
var bpjs = 250000;
var pajak = 0.025;
var hasilpajak = pajak*gaji;
var hasiltunjangan = transport*hari;
var hasilpotongan = hasilpajak+bpjs+infak;
var perhitungangaji = gaji-hasilpotongan+hasiltunjangan;

console.log("Gaji kotor = " + gaji);
console.log("====================");
console.log("Potongan pajak 2,5% = " + (hasilpajak));
console.log("Potongan BPJS = " + bpjs);
console.log("Potongan infak = " + infak);
console.log("====================");
console.log("Total potongan : "+"Rp." +(hasilpajak+bpjs+infak));
console.log("====================");
console.log("Tunjangan transport "+"Rp." + transport);
console.log("Total hari kerja : "  +  hari);
console.log("====================");
console.log("Total Tunjangan : "  + (transport*hari));
console.log("====================");
console.log("perhitungan gaji ");
console.log("(Gaji Kotor - Potongan) + Tunjangan");
console.log("("+gaji+"-"+hasilpotongan+") = "+hasiltunjangan);
console.log("====================");
console.log("Gaji bersih = " +"Rp." + perhitungangaji);